name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  go-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ["1.14", "1.15"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: go test
        run: |
          go test -race -v ./...
